# Collaborative Remaining Useful Life ($\textit{RUL}$) estimation of turbofan engines

This repository contains code for simulating a collaborative prognostics problem, the Remaining Useful Life estimation of turbofan engines located at different parties (airlines). Collaborative problem simulates the participation of three airlines differing in flight lengths (Flight Classes): short-length flights (i.e., flight class 1), medium-length flights (i.e., flight class 2), or long-length flights (i.e., flight class 2).

| Flight Class   | Flight Length [h]
| :-----------:  | :-----------:    
| 1              |    1 to 3        
| 2              |    3 to 5        
| 3              |    5 to 7  

Those flight classes comes from the **new** C-MAPSS (Commercial Modular Aero-Propulsion System Simulation) dataset from NASA for aircraft engines. More details about the generation process can be found at https://www.mdpi.com/2306-5729/6/1/5.  

This notebook reused the [inception-based CNN network](https://doi.org/10.36001/phmconf.2021.v13i1.3109) and its pre-processing precedures to estimate the $\textit{RUL}$ of engines experiencing a determined flight class (FC). Datasets (FC*_dev.h5 and FC*_test.h5) for each FC are generated by executing:

- 1) Spliting a given dataset by Flight Class.ipynb
- 2) Concatenating datasets by Flight Class.ipynb

The collaborative problem, simulated using the [Federated Label Synchornization FedLabSync algorithm](https://doi.org/10.1007/s10845-023-02298-8), uses [Tensorflow tf.distribute.Strategy](https://www.tensorflow.org/guide/distributed_training) to distribute the work along multiple GPUs.  To run this code, a cluster of GPUs must be configured. Hyperparameters for distributed Machine Learning experiments are configured in "Global Variables" Section, e.g.,  number of nodes (parties participating in the ferated network) and the current node for which the federated model is trained. 

Federated experiments are implemented in:

- Collaborative prediction using NCMAPSS.ipynb

# Prerequisites 

- Python > 3.10
- Anaconda > 3.11 
- CUDA Toolkit compatible with tensorflow==2.10.0
- cuDNN Library  compatible with tensorflow==2.10.0
- Cluster of GPUs to configure `tf.distribute.Strategy`

# Installation guide

`git clone https://github.com/rhllasag/fedLabSync.git`

## Conda Environment 

`cd fedLabSync`

`conda env create --file environment.yaml`

`conda activate fedLabSync`

`pip install fedLabSync`

`pip install psg_utils==0.1.6`

`pip install typing-extensions==4.6.0`

`pip install tables`

`pip install tables`

`pip install carbontracker`

`pip install tensorflow_addons`

`pip install seaborn`

## Pypi Installation in case of fedLabSync unavailability

`python setup.py bdist_wheel`

`pip install dist/fedLabSync-0.0.3-py3-none-any.whl --force-reinstall`

## Download current repository and run current notebooks

`cd ..`

`git clone https://github.com/rhllasag/fedLabSyncNCMAPSS.git`

